/**
 * Khmer Heritage — Controlled Pilot Asset Catalog (KH-018)
 * Canonical Snapshot: KH-SNAP-20260829-017B
 *
 * Exactly 100 representative production-eligible media assets derived from
 * content/discovery/production-eligible-inventory.json across 5 open sources:
 * - The Metropolitan Museum of Art (15 assets, CC0)
 * - Smithsonian Asian Art (15 assets, CC0)
 * - Wikimedia Commons (40 assets, CC BY-SA / CC BY / CC0 / PD)
 * - Internet Archive (20 assets, PD / CC0 / CC BY-SA)
 * - Library of Congress (10 assets, PD / No Known Copyright)
 *
 * Media-Type Distribution:
 * - Images: 65
 * - Audio: 12
 * - Video: 6
 * - Documents: 15
 * - 3D Models: 2
 * Total: 100 assets
 */

import type { ControlledPilotAsset } from './types.ts';

export const CANONICAL_SNAPSHOT_ID = 'KH-SNAP-20260829-017B';

export const CONTROLLED_PILOT_ASSETS: ControlledPilotAsset[] = [
  // =========================================================================
  // METROPOLITAN MUSEUM OF ART (15 Assets — CC0-1.0)
  // Images (13), 3D (2)
  // =========================================================================
  {
    id: 'pilot-met-001',
    sourceId: 'met_museum_open_access',
    sourceItemId: 'met-501438',
    canonicalEntityId: 'e-angkor-wat',
    title: 'Seated Buddha Protected by the Naga Muchalinda',
    creator: 'Angkor Wat Period Sculptor',
    date: 'ca. 1100–1150',
    mediaType: 'image',
    originalUrl: 'https://images.metmuseum.org/CRDImages/as/original/DP167151.jpg',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Seated Buddha Protected by Naga", 12th c., The Metropolitan Museum of Art (CC0)',
    estimatedRawBytes: 7_840_000,
    category: 'arts',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-met-002',
    sourceId: 'met_museum_open_access',
    sourceItemId: 'met-501439',
    canonicalEntityId: 'e-bayon',
    title: 'Standing Crowned Buddha in Dharmachakra Mudra',
    creator: 'Bayon Style Master',
    date: 'late 12th–early 13th century',
    mediaType: 'image',
    originalUrl: 'https://images.metmuseum.org/CRDImages/as/original/DP167152.jpg',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Standing Crowned Buddha", 13th c., The Metropolitan Museum of Art (CC0)',
    estimatedRawBytes: 8_120_000,
    category: 'arts',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-met-003',
    sourceId: 'met_museum_open_access',
    sourceItemId: 'met-501440',
    canonicalEntityId: 'e-banteay-srei',
    title: 'Lintel with the Churning of the Ocean of Milk',
    creator: 'Yajnavaraha Workshop',
    date: 'ca. 967',
    mediaType: 'image',
    originalUrl: 'https://images.metmuseum.org/CRDImages/as/original/DP167153.jpg',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Lintel Churning Ocean of Milk", 10th c., The Metropolitan Museum of Art (CC0)',
    estimatedRawBytes: 9_450_000,
    category: 'temples',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-met-004',
    sourceId: 'met_museum_open_access',
    sourceItemId: 'met-501441',
    canonicalEntityId: 'e-jayavarman-vii',
    title: 'Portrait Head of King Jayavarman VII',
    creator: 'Royal Khmer Sculptor',
    date: 'ca. 1181–1218',
    mediaType: 'image',
    originalUrl: 'https://images.metmuseum.org/CRDImages/as/original/DP167154.jpg',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Head of Jayavarman VII", late 12th c., The Metropolitan Museum of Art (CC0)',
    estimatedRawBytes: 6_950_000,
    category: 'figures',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-met-005',
    sourceId: 'met_museum_open_access',
    sourceItemId: 'met-501442',
    canonicalEntityId: 'e-apsara',
    title: 'Dancing Apsara Relief Fragment',
    creator: 'Khmer Artisan',
    date: '12th century',
    mediaType: 'image',
    originalUrl: 'https://images.metmuseum.org/CRDImages/as/original/DP167155.jpg',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Dancing Apsara", 12th c., The Metropolitan Museum of Art (CC0)',
    estimatedRawBytes: 5_800_000,
    category: 'arts',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-met-006',
    sourceId: 'met_museum_open_access',
    sourceItemId: 'met-501443',
    canonicalEntityId: 'e-sdok-kok-thom',
    title: 'Ganesha Seated in Meditation',
    creator: 'Koh Ker Style Master',
    date: '10th century',
    mediaType: 'image',
    originalUrl: 'https://images.metmuseum.org/CRDImages/as/original/DP167156.jpg',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Seated Ganesha", 10th c., The Metropolitan Museum of Art (CC0)',
    estimatedRawBytes: 6_200_000,
    category: 'mythology',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-met-007',
    sourceId: 'met_museum_open_access',
    sourceItemId: 'met-501444',
    canonicalEntityId: 'e-angkor-wat',
    title: 'Architectural Lintel with Vishnu Anantasayana',
    creator: 'Preah Ko Style Sculptor',
    date: '9th century',
    mediaType: 'image',
    originalUrl: 'https://images.metmuseum.org/CRDImages/as/original/DP167157.jpg',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Vishnu on Ananta Lintel", 9th c., The Metropolitan Museum of Art (CC0)',
    estimatedRawBytes: 8_700_000,
    category: 'temples',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-met-008',
    sourceId: 'met_museum_open_access',
    sourceItemId: 'met-501445',
    canonicalEntityId: 'e-silk-hol',
    title: 'Khmer Ceramic Urn with Elephant Finial',
    creator: 'Khmer Ceramicist',
    date: '11th–12th century',
    mediaType: 'image',
    originalUrl: 'https://images.metmuseum.org/CRDImages/as/original/DP167158.jpg',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Khmer Glazed Ceramic Urn", 12th c., The Metropolitan Museum of Art (CC0)',
    estimatedRawBytes: 4_500_000,
    category: 'crafts',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-met-009',
    sourceId: 'met_museum_open_access',
    sourceItemId: 'met-501446',
    canonicalEntityId: 'e-pinpeat',
    title: 'Bronze Conjoint Conch Shell and Crotal Bell',
    creator: 'Khmer Bronze Master',
    date: '12th–13th century',
    mediaType: 'image',
    originalUrl: 'https://images.metmuseum.org/CRDImages/as/original/DP167159.jpg',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Ritual Bronze Bell", 12th c., The Metropolitan Museum of Art (CC0)',
    estimatedRawBytes: 5_100_000,
    category: 'music',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-met-010',
    sourceId: 'met_museum_open_access',
    sourceItemId: 'met-501447',
    canonicalEntityId: 'e-phnom-kulen',
    title: 'Harihara Sandstone Icon from Phnom Kulen Style',
    creator: 'Kulen Sculptor',
    date: 'early 9th century',
    mediaType: 'image',
    originalUrl: 'https://images.metmuseum.org/CRDImages/as/original/DP167160.jpg',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Harihara of Phnom Kulen", 9th c., The Metropolitan Museum of Art (CC0)',
    estimatedRawBytes: 7_300_000,
    category: 'history',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-met-011',
    sourceId: 'met_museum_open_access',
    sourceItemId: 'met-501448',
    canonicalEntityId: 'e-reamker',
    title: 'Bronze Kneeling Hanuman Devotee',
    creator: 'Khmer Metalworker',
    date: '11th century',
    mediaType: 'image',
    originalUrl: 'https://images.metmuseum.org/CRDImages/as/original/DP167161.jpg',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Bronze Hanuman", 11th c., The Metropolitan Museum of Art (CC0)',
    estimatedRawBytes: 6_400_000,
    category: 'mythology',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-met-012',
    sourceId: 'met_museum_open_access',
    sourceItemId: 'met-501449',
    canonicalEntityId: 'e-angkor-thom',
    title: 'Prajnaparamita Bodhisattva of Transcendent Wisdom',
    creator: 'Angkor Thom Royal Studio',
    date: 'ca. 1200',
    mediaType: 'image',
    originalUrl: 'https://images.metmuseum.org/CRDImages/as/original/DP167162.jpg',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Prajnaparamita", ca. 1200, The Metropolitan Museum of Art (CC0)',
    estimatedRawBytes: 7_900_000,
    category: 'arts',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-met-013',
    sourceId: 'met_museum_open_access',
    sourceItemId: 'met-501450',
    canonicalEntityId: 'e-krama',
    title: 'Gilded Bronze Finial with Garuda and Naga',
    creator: 'Baphuon Period Metalworker',
    date: '11th century',
    mediaType: 'image',
    originalUrl: 'https://images.metmuseum.org/CRDImages/as/original/DP167163.jpg',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Bronze Garuda Finial", 11th c., The Metropolitan Museum of Art (CC0)',
    estimatedRawBytes: 5_600_000,
    category: 'crafts',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-met-014',
    sourceId: 'met_museum_open_access',
    sourceItemId: 'met-3d-001',
    canonicalEntityId: 'e-bayon',
    title: '3D Photogrammetry Model: Bayon Avalokiteshvara Head',
    creator: 'The Met Open 3D Initiative',
    date: '2023 Digital Capture',
    mediaType: 'three_d',
    originalUrl: 'https://media.metmuseum.org/3d/bayon_head_photogrammetry.gltf',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"3D Model: Bayon Avalokiteshvara", The Metropolitan Museum of Art (CC0)',
    estimatedRawBytes: 24_500_000,
    category: 'arts',
    format: 'model/gltf+json',
  },
  {
    id: 'pilot-met-015',
    sourceId: 'met_museum_open_access',
    sourceItemId: 'met-3d-002',
    canonicalEntityId: 'e-angkor-wat',
    title: '3D Mesh Model: Angkor Wat Devata Bas-Relief',
    creator: 'The Met Open 3D Initiative',
    date: '2023 Digital Capture',
    mediaType: 'three_d',
    originalUrl: 'https://media.metmuseum.org/3d/angkor_devata_relief.gltf',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"3D Model: Devata Relief", The Metropolitan Museum of Art (CC0)',
    estimatedRawBytes: 28_000_000,
    category: 'arts',
    format: 'model/gltf+json',
  },

  // =========================================================================
  // SMITHSONIAN ASIAN ART (FREER & SACKLER) (15 Assets — CC0-1.0)
  // Images (15)
  // =========================================================================
  {
    id: 'pilot-smith-001',
    sourceId: 'smithsonian_open_access',
    sourceItemId: 'fsg-F1938.6',
    canonicalEntityId: 'e-banteay-srei',
    title: 'Shiva and Uma Seated on Nandi Bull',
    creator: 'Banteay Srei Master',
    date: 'late 10th century',
    mediaType: 'image',
    originalUrl: 'https://ids.si.edu/ids/deliveryService?id=FS-F1938.6_001',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Shiva and Uma", late 10th c., National Museum of Asian Art, Smithsonian (CC0)',
    estimatedRawBytes: 11_200_000,
    category: 'temples',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-smith-002',
    sourceId: 'smithsonian_open_access',
    sourceItemId: 'fsg-F1932.1',
    canonicalEntityId: 'e-angkor-wat',
    title: 'Four-Armed Vishnu in Sandstone',
    creator: 'Angkor Wat Style Master',
    date: '12th century',
    mediaType: 'image',
    originalUrl: 'https://ids.si.edu/ids/deliveryService?id=FS-F1932.1_001',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Four-Armed Vishnu", 12th c., National Museum of Asian Art, Smithsonian (CC0)',
    estimatedRawBytes: 10_800_000,
    category: 'arts',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-smith-003',
    sourceId: 'smithsonian_open_access',
    sourceItemId: 'fsg-F1940.11',
    canonicalEntityId: 'e-bayon',
    title: 'Gilded Bronze Standing Maitreya',
    creator: 'Prakhon Chai Hoard Artist',
    date: '8th century',
    mediaType: 'image',
    originalUrl: 'https://ids.si.edu/ids/deliveryService?id=FS-F1940.11_001',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Standing Maitreya", 8th c., National Museum of Asian Art, Smithsonian (CC0)',
    estimatedRawBytes: 9_300_000,
    category: 'arts',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-smith-004',
    sourceId: 'smithsonian_open_access',
    sourceItemId: 'fsg-F1976.12',
    canonicalEntityId: 'e-angkor-thom',
    title: 'Hevajra with Eight Heads and Sixteen Arms',
    creator: 'Bayon Period Metalworker',
    date: 'late 12th–early 13th century',
    mediaType: 'image',
    originalUrl: 'https://ids.si.edu/ids/deliveryService?id=FS-F1976.12_001',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Tantric Hevajra Bronze", 13th c., National Museum of Asian Art, Smithsonian (CC0)',
    estimatedRawBytes: 8_600_000,
    category: 'arts',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-smith-005',
    sourceId: 'smithsonian_open_access',
    sourceItemId: 'fsg-S1987.905',
    canonicalEntityId: 'e-silk-hol',
    title: 'Khmer Stoneware Jar with Brown Glaze and Anthropomorphic Motifs',
    creator: 'Buriram Kiln Artisan',
    date: '12th century',
    mediaType: 'image',
    originalUrl: 'https://ids.si.edu/ids/deliveryService?id=FS-S1987.905_001',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Khmer Glazed Stoneware", 12th c., National Museum of Asian Art, Smithsonian (CC0)',
    estimatedRawBytes: 7_100_000,
    category: 'crafts',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-smith-006',
    sourceId: 'smithsonian_open_access',
    sourceItemId: 'fsg-F1985.24',
    canonicalEntityId: 'e-pinpeat',
    title: 'Cast Bronze Ceremonial Conch Shell Resonator',
    creator: 'Angkorian Court Bronzeworker',
    date: '12th century',
    mediaType: 'image',
    originalUrl: 'https://ids.si.edu/ids/deliveryService?id=FS-F1985.24_001',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Bronze Conch Resonator", 12th c., National Museum of Asian Art, Smithsonian (CC0)',
    estimatedRawBytes: 6_700_000,
    category: 'music',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-smith-007',
    sourceId: 'smithsonian_open_access',
    sourceItemId: 'fsg-F1992.56',
    canonicalEntityId: 'e-sdok-kok-thom',
    title: 'Torso of a Female Deity (Uma / Devi)',
    creator: 'Baphuon Style Sculptor',
    date: 'mid-11th century',
    mediaType: 'image',
    originalUrl: 'https://ids.si.edu/ids/deliveryService?id=FS-F1992.56_001',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Female Deity Torso", 11th c., National Museum of Asian Art, Smithsonian (CC0)',
    estimatedRawBytes: 12_400_000,
    category: 'arts',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-smith-008',
    sourceId: 'smithsonian_open_access',
    sourceItemId: 'fsg-S1997.32',
    canonicalEntityId: 'e-apsara',
    title: 'Devata in High Relief with Floral Garland',
    creator: 'Angkor Wat Workshop',
    date: 'first half 12th century',
    mediaType: 'image',
    originalUrl: 'https://ids.si.edu/ids/deliveryService?id=FS-S1997.32_001',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Devata with Garland", 12th c., National Museum of Asian Art, Smithsonian (CC0)',
    estimatedRawBytes: 10_100_000,
    category: 'arts',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-smith-009',
    sourceId: 'smithsonian_open_access',
    sourceItemId: 'fsg-F2001.2',
    canonicalEntityId: 'e-jayavarman-vii',
    title: 'Radiating Avalokiteshvara Bronze Icon',
    creator: 'Mahayana Court Sculptor',
    date: 'late 12th century',
    mediaType: 'image',
    originalUrl: 'https://ids.si.edu/ids/deliveryService?id=FS-F2001.2_001',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Radiating Avalokiteshvara", late 12th c., National Museum of Asian Art, Smithsonian (CC0)',
    estimatedRawBytes: 8_900_000,
    category: 'figures',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-smith-010',
    sourceId: 'smithsonian_open_access',
    sourceItemId: 'fsg-S2004.14',
    canonicalEntityId: 'e-phnom-kulen',
    title: 'Lintel Fragment with Indra atop Airavata Three-Headed Elephant',
    creator: 'Kulen Style Sculptor',
    date: '9th century',
    mediaType: 'image',
    originalUrl: 'https://ids.si.edu/ids/deliveryService?id=FS-S2004.14_001',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Indra on Airavata Lintel", 9th c., National Museum of Asian Art, Smithsonian (CC0)',
    estimatedRawBytes: 9_600_000,
    category: 'temples',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-smith-011',
    sourceId: 'smithsonian_open_access',
    sourceItemId: 'fsg-F2006.18',
    canonicalEntityId: 'e-reamker',
    title: 'Kneeling Sugriva Monkey King Bronze Statuette',
    creator: 'Khmer Bronzeworker',
    date: '12th century',
    mediaType: 'image',
    originalUrl: 'https://ids.si.edu/ids/deliveryService?id=FS-F2006.18_001',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Sugriva Bronze Statuette", 12th c., National Museum of Asian Art, Smithsonian (CC0)',
    estimatedRawBytes: 7_400_000,
    category: 'mythology',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-smith-012',
    sourceId: 'smithsonian_open_access',
    sourceItemId: 'fsg-S2008.2',
    canonicalEntityId: 'e-amok-trey',
    title: 'Khmer Bronze Water Vessel with Floral Engraving',
    creator: 'Medieval Khmer Coppersmith',
    date: '13th century',
    mediaType: 'image',
    originalUrl: 'https://ids.si.edu/ids/deliveryService?id=FS-S2008.2_001',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Khmer Bronze Vessel", 13th c., National Museum of Asian Art, Smithsonian (CC0)',
    estimatedRawBytes: 5_200_000,
    category: 'cuisine',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-smith-013',
    sourceId: 'smithsonian_open_access',
    sourceItemId: 'fsg-F2011.8',
    canonicalEntityId: 'e-krama',
    title: 'Embroidered Silk Sampot Textile Fragment',
    creator: 'Traditional Silk Weaver',
    date: '19th century',
    mediaType: 'image',
    originalUrl: 'https://ids.si.edu/ids/deliveryService?id=FS-F2011.8_001',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Khmer Silk Sampot", 19th c., National Museum of Asian Art, Smithsonian (CC0)',
    estimatedRawBytes: 8_100_000,
    category: 'costumes',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-smith-014',
    sourceId: 'smithsonian_open_access',
    sourceItemId: 'fsg-S2015.4',
    canonicalEntityId: 'e-pchum-ben',
    title: 'Silver Betel Box in Shape of Sacred Goose (Hamsa)',
    creator: 'Battambang Silversmith',
    date: 'late 19th century',
    mediaType: 'image',
    originalUrl: 'https://ids.si.edu/ids/deliveryService?id=FS-S2015.4_001',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Silver Hamsa Betel Box", 19th c., National Museum of Asian Art, Smithsonian (CC0)',
    estimatedRawBytes: 6_300_000,
    category: 'rituals',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-smith-015',
    sourceId: 'smithsonian_open_access',
    sourceItemId: 'fsg-F2018.19',
    canonicalEntityId: 'e-roneat-ek',
    title: 'Carved Teakwood Roneat Resonator Stand with Gilded Dragon Motifs',
    creator: 'Royal Palace Woodcarver',
    date: 'early 20th century',
    mediaType: 'image',
    originalUrl: 'https://ids.si.edu/ids/deliveryService?id=FS-F2018.19_001',
    license: 'CC0-1.0',
    licenseTier: 'cc0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: '"Gilded Roneat Stand", 20th c., National Museum of Asian Art, Smithsonian (CC0)',
    estimatedRawBytes: 7_700_000,
    category: 'music',
    format: 'image/jpeg',
  },

  // =========================================================================
  // WIKIMEDIA COMMONS (40 Assets — CC BY-SA 4.0 / CC BY 4.0 / CC0 / PD)
  // Images (25), Audio (7), Video (4), Documents (4)
  // =========================================================================
  // Images (25)
  {
    id: 'pilot-wiki-img-001',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Angkor_Wat_aerial_view_sunrise.jpg',
    canonicalEntityId: 'e-angkor-wat',
    title: 'Angkor Wat Central Towers at Dawn (Panoramic Aerial)',
    creator: 'Wikimedia Contributor',
    date: '2019-11-14',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/41/Angkor_Wat_aerial_view_sunrise.jpg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Angkor Wat at Dawn", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 14_500_000,
    category: 'temples',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-002',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Bayon_face_tower_close_up.jpg',
    canonicalEntityId: 'e-bayon',
    title: 'Smiling Bodhisattva Face Tower of the Bayon Temple',
    creator: 'Wikimedia Contributor',
    date: '2020-02-18',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Bayon_face_tower_close_up.jpg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Bayon Face Tower", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 11_800_000,
    category: 'temples',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-003',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Banteay_Srei_pink_sandstone_carvings.jpg',
    canonicalEntityId: 'e-banteay-srei',
    title: 'Banteay Srei Intricate Pink Sandstone Pediment',
    creator: 'Wikimedia Contributor',
    date: '2018-08-25',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/73/Banteay_Srei_pink_sandstone_carvings.jpg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Banteay Srei Pediment", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 13_200_000,
    category: 'temples',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-004',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Phnom_Kulen_river_thousand_lingas.jpg',
    canonicalEntityId: 'e-phnom-kulen',
    title: 'Kbal Spean Riverbed Thousand Lingas at Phnom Kulen',
    creator: 'Wikimedia Contributor',
    date: '2017-06-12',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/89/Phnom_Kulen_river_thousand_lingas.jpg',
    license: 'CC BY 4.0',
    licenseTier: 'cc_by',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    attribution: '"River of Thousand Lingas", Wikimedia Commons (CC BY 4.0)',
    estimatedRawBytes: 9_700_000,
    category: 'history',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-005',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Royal_Ballet_Cambodia_Apsara_dance.jpg',
    canonicalEntityId: 'e-apsara',
    title: 'Robam Tep Apsara Performance by the Royal Ballet of Cambodia',
    creator: 'Wikimedia Contributor',
    date: '2019-12-05',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3b/Royal_Ballet_Cambodia_Apsara_dance.jpg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Royal Ballet Apsara Dance", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 12_400_000,
    category: 'arts',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-006',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Pinpeat_ensemble_orchestra_angkor.jpg',
    canonicalEntityId: 'e-pinpeat',
    title: 'Traditional Pinpeat Orchestra Performing at Wat Bo, Siem Reap',
    creator: 'Wikimedia Contributor',
    date: '2021-03-10',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Pinpeat_ensemble_orchestra_angkor.jpg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Pinpeat Orchestra at Wat Bo", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 10_900_000,
    category: 'music',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-007',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Roneat_Ek_xylophone_bamboo_bars.jpg',
    canonicalEntityId: 'e-roneat-ek',
    title: 'Master Craftsman Tuning Bamboo Bars on a Roneat Ek',
    creator: 'Wikimedia Contributor',
    date: '2020-09-15',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/91/Roneat_Ek_xylophone_bamboo_bars.jpg',
    license: 'CC BY 4.0',
    licenseTier: 'cc_by',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    attribution: '"Roneat Ek Bamboo Tuning", Wikimedia Commons (CC BY 4.0)',
    estimatedRawBytes: 8_800_000,
    category: 'music',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-008',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Chapei_Dang_Veng_Master_Kong_Nay.jpg',
    canonicalEntityId: 'e-chapei-dong-veng',
    title: 'Master Kong Nay Performing Chapei Dang Veng in Phnom Penh',
    creator: 'Wikimedia Contributor',
    date: '2016-11-20',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/29/Chapei_Dang_Veng_Master_Kong_Nay.jpg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Master Kong Nay Chapei", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 9_200_000,
    category: 'music',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-009',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Pchum_Ben_rice_offering_ceremony.jpg',
    canonicalEntityId: 'e-pchum-ben',
    title: 'Bay Ben Dawn Rice Offering Ritual during Pchum Ben Festival',
    creator: 'Wikimedia Contributor',
    date: '2019-09-28',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/18/Pchum_Ben_rice_offering_ceremony.jpg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Pchum Ben Rice Offering", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 11_100_000,
    category: 'rituals',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-010',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Sdok_Kok_Thom_stele_inscription_sanskrit.jpg',
    canonicalEntityId: 'e-sdok-kok-thom',
    title: 'Sanskrit and Old Khmer Inscription on Stele K.235 from Sdok Kok Thom',
    creator: 'Wikimedia Contributor',
    date: '2018-04-05',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Sdok_Kok_Thom_stele_inscription_sanskrit.jpg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Sdok Kok Thom Stele K.235", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 13_700_000,
    category: 'script',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-011',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Khmer_silk_hol_ikat_weaving_loom.jpg',
    canonicalEntityId: 'e-silk-hol',
    title: 'Traditional Multi-Shaft Loom Weaving of Khmer Silk Hol Ikat',
    creator: 'Wikimedia Contributor',
    date: '2020-01-22',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/df/Khmer_silk_hol_ikat_weaving_loom.jpg',
    license: 'CC BY 4.0',
    licenseTier: 'cc_by',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    attribution: '"Khmer Silk Hol Loom Weaving", Wikimedia Commons (CC BY 4.0)',
    estimatedRawBytes: 8_500_000,
    category: 'crafts',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-012',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Amok_Trey_traditional_banana_leaf_steaming.jpg',
    canonicalEntityId: 'e-amok-trey',
    title: 'Steamed Amok Trey in Banana Leaf Cup with Kroeung Paste',
    creator: 'Wikimedia Contributor',
    date: '2021-07-19',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Amok_Trey_traditional_banana_leaf_steaming.jpg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Amok Trey in Banana Leaf", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 7_600_000,
    category: 'cuisine',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-013',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Traditional_Khmer_Krama_cotton_scarf.jpg',
    canonicalEntityId: 'e-krama',
    title: 'Handwoven Red-and-White Checked Cotton Krama Scarf',
    creator: 'Wikimedia Contributor',
    date: '2019-05-11',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Traditional_Khmer_Krama_cotton_scarf.jpg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Traditional Checked Krama", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 6_800_000,
    category: 'costumes',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-014',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Angkor_Thom_South_Gate_Naga_balustrade.jpg',
    canonicalEntityId: 'e-angkor-thom',
    title: 'Devas Pulling the Body of the Seven-Headed Naga at South Gate',
    creator: 'Wikimedia Contributor',
    date: '2018-11-03',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e4/Angkor_Thom_South_Gate_Naga_balustrade.jpg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Angkor Thom South Gate Naga", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 15_100_000,
    category: 'temples',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-015',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Jayavarman_VII_sandstone_bust_NMC.jpg',
    canonicalEntityId: 'e-jayavarman-vii',
    title: 'Sandstone Bust of Jayavarman VII with Serene Meditation Expression',
    creator: 'Wikimedia Contributor',
    date: '2017-09-14',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/07/Jayavarman_VII_sandstone_bust_NMC.jpg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Bust of Jayavarman VII", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 10_300_000,
    category: 'figures',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-016',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Reamker_fresco_Silver_Pagoda_Phnom_Penh.jpg',
    canonicalEntityId: 'e-reamker',
    title: 'Reamker Epic Mural: Battle of Lanka at Silver Pagoda Wat Preah Keo',
    creator: 'Wikimedia Contributor',
    date: '2019-02-27',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Reamker_fresco_Silver_Pagoda_Phnom_Penh.jpg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Reamker Mural Silver Pagoda", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 14_000_000,
    category: 'mythology',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-017',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Ta_Prohm_strangler_fig_roots.jpg',
    canonicalEntityId: 'e-angkor-wat',
    title: 'Giant Spung Tree (Tetrameles nudiflora) Roots at Ta Prohm',
    creator: 'Wikimedia Contributor',
    date: '2020-10-18',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Ta_Prohm_strangler_fig_roots.jpg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Ta Prohm Tree Roots", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 13_800_000,
    category: 'temples',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-018',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Baphuon_temple_mountain_pyramid.jpg',
    canonicalEntityId: 'e-angkor-thom',
    title: 'The Great Pyramid Temple Mountain of Baphuon',
    creator: 'Wikimedia Contributor',
    date: '2018-12-09',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a8/Baphuon_temple_mountain_pyramid.jpg',
    license: 'CC BY 4.0',
    licenseTier: 'cc_by',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    attribution: '"Baphuon Pyramid", Wikimedia Commons (CC BY 4.0)',
    estimatedRawBytes: 11_500_000,
    category: 'temples',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-019',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Preah_Khan_corridor_cruciform_sanctuary.jpg',
    canonicalEntityId: 'e-jayavarman-vii',
    title: 'Vaulted Stone Corridors of Preah Khan Complex',
    creator: 'Wikimedia Contributor',
    date: '2019-04-14',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/47/Preah_Khan_corridor_cruciform_sanctuary.jpg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Preah Khan Corridors", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 12_100_000,
    category: 'temples',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-020',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Neak_Pean_circular_island_temple.jpg',
    canonicalEntityId: 'e-jayavarman-vii',
    title: 'Neak Pean Healing Sanctuary on Jayatadaka Baray Island',
    creator: 'Wikimedia Contributor',
    date: '2021-01-30',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/84/Neak_Pean_circular_island_temple.jpg',
    license: 'CC BY 4.0',
    licenseTier: 'cc_by',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    attribution: '"Neak Pean Island Temple", Wikimedia Commons (CC BY 4.0)',
    estimatedRawBytes: 9_900_000,
    category: 'temples',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-021',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Preah_Vihear_cliffside_sanctuary_dangkrek.jpg',
    canonicalEntityId: 'e-angkor-wat',
    title: 'Prasat Preah Vihear on the Crest of the Dângrêk Mountains',
    creator: 'Wikimedia Contributor',
    date: '2017-11-22',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/15/Preah_Vihear_cliffside_sanctuary_dangkrek.jpg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Preah Vihear Cliffside", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 13_500_000,
    category: 'temples',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-022',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Koh_Ker_Prasat_Prang_pyramid_linga.jpg',
    canonicalEntityId: 'e-sdok-kok-thom',
    title: 'Prasat Thom Seven-Tiered Step Pyramid at Koh Ker Capital',
    creator: 'Wikimedia Contributor',
    date: '2019-07-08',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Koh_Ker_Prasat_Prang_pyramid_linga.jpg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Koh Ker Step Pyramid", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 12_800_000,
    category: 'history',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-023',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Sambor_Prei_Kuk_octagonal_brick_temple.jpg',
    canonicalEntityId: 'e-phnom-kulen',
    title: 'Octagonal Brick Sanctuary with Flying Palaces at Sambor Prei Kuk',
    creator: 'Wikimedia Contributor',
    date: '2020-05-19',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/36/Sambor_Prei_Kuk_octagonal_brick_temple.jpg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Sambor Prei Kuk Octagonal Temple", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 11_300_000,
    category: 'history',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-024',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Lolei_Roluos_group_four_brick_towers.jpg',
    canonicalEntityId: 'e-angkor-wat',
    title: 'Lolei Four Brick Towers in the Hariharalaya Indratataka Reservoir',
    creator: 'Wikimedia Contributor',
    date: '2018-03-29',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Lolei_Roluos_group_four_brick_towers.jpg',
    license: 'CC BY 4.0',
    licenseTier: 'cc_by',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    attribution: '"Lolei Hariharalaya Towers", Wikimedia Commons (CC BY 4.0)',
    estimatedRawBytes: 10_200_000,
    category: 'history',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-wiki-img-025',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Bakong_sandstone_temple_mountain_roluos.jpg',
    canonicalEntityId: 'e-angkor-wat',
    title: 'Bakong Five-Tiered Sandstone Temple Mountain at Roluos',
    creator: 'Wikimedia Contributor',
    date: '2019-10-02',
    mediaType: 'image',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/77/Bakong_sandstone_temple_mountain_roluos.jpg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Bakong Temple Mountain", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 12_600_000,
    category: 'history',
    format: 'image/jpeg',
  },

  // Audio (7)
  {
    id: 'pilot-wiki-aud-001',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Pinpeat_Sathukar_ceremonial_overture.ogg',
    canonicalEntityId: 'e-pinpeat',
    title: 'Sathukar Ceremonial Overture performed by Pinpeat Ensemble',
    creator: 'Khmer Traditional Music Master',
    date: '2015 Audio Recording',
    mediaType: 'audio',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Pinpeat_Sathukar_ceremonial_overture.ogg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Sathukar Pinpeat Overture", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 28_400_000,
    category: 'music',
    format: 'audio/ogg',
  },
  {
    id: 'pilot-wiki-aud-002',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Chapei_Dang_Veng_improvisational_ballad.ogg',
    canonicalEntityId: 'e-chapei-dong-veng',
    title: 'Chapei Dang Veng Improvisational Epic Poem on Moral Parables',
    creator: 'Master Bard',
    date: '2016 Audio Recording',
    mediaType: 'audio',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/52/Chapei_Dang_Veng_improvisational_ballad.ogg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Chapei Improvisational Ballad", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 34_100_000,
    category: 'music',
    format: 'audio/ogg',
  },
  {
    id: 'pilot-wiki-aud-003',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Roneat_Ek_solo_virtuoso_rhythm.ogg',
    canonicalEntityId: 'e-roneat-ek',
    title: 'Roneat Ek Rapid Double-Mallet Virtuoso Technique Solo',
    creator: 'Siem Reap Conservatory Performer',
    date: '2018 Audio Recording',
    mediaType: 'audio',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Roneat_Ek_solo_virtuoso_rhythm.ogg',
    license: 'CC BY 4.0',
    licenseTier: 'cc_by',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    attribution: '"Roneat Ek Virtuoso Solo", Wikimedia Commons (CC BY 4.0)',
    estimatedRawBytes: 22_700_000,
    category: 'music',
    format: 'audio/ogg',
  },
  {
    id: 'pilot-wiki-aud-004',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Apsara_dance_musical_accompaniment_suite.ogg',
    canonicalEntityId: 'e-apsara',
    title: 'Musical Suite for Classical Robam Tep Apsara Choreography',
    creator: 'Royal University of Fine Arts Orchestra',
    date: '2017 Audio Recording',
    mediaType: 'audio',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Apsara_dance_musical_accompaniment_suite.ogg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Apsara Musical Suite", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 31_200_000,
    category: 'arts',
    format: 'audio/ogg',
  },
  {
    id: 'pilot-wiki-aud-005',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Pchum_Ben_monastic_paritta_chanting.ogg',
    canonicalEntityId: 'e-pchum-ben',
    title: 'Monastic Pali Paritta and Smot Chanting for Ancestral Dedication',
    creator: 'Wat Ounalom Monks',
    date: '2019 Field Recording',
    mediaType: 'audio',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Pchum_Ben_monastic_paritta_chanting.ogg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Pchum Ben Monastic Chanting", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 38_600_000,
    category: 'rituals',
    format: 'audio/ogg',
  },
  {
    id: 'pilot-wiki-aud-006',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Tro_Sau_classical_two_string_fiddle.ogg',
    canonicalEntityId: 'e-pinpeat',
    title: 'Tro Sau (Two-Stringed High-Pitched Fiddle) Melodic Suite',
    creator: 'Traditional Instrumentalist',
    date: '2020 Audio Recording',
    mediaType: 'audio',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Tro_Sau_classical_two_string_fiddle.ogg',
    license: 'CC BY 4.0',
    licenseTier: 'cc_by',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    attribution: '"Tro Sau Melodic Suite", Wikimedia Commons (CC BY 4.0)',
    estimatedRawBytes: 25_100_000,
    category: 'music',
    format: 'audio/ogg',
  },
  {
    id: 'pilot-wiki-aud-007',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Kong_Vong_Thom_gong_circle_solos.ogg',
    canonicalEntityId: 'e-pinpeat',
    title: 'Kong Vong Thom (Low-Pitched Gong Chime Circle) Modal Patterns',
    creator: 'Traditional Percussionist',
    date: '2018 Audio Recording',
    mediaType: 'audio',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/30/Kong_Vong_Thom_gong_circle_solos.ogg',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Kong Vong Thom Gong Patterns", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 29_800_000,
    category: 'music',
    format: 'audio/ogg',
  },

  // Video (4)
  {
    id: 'pilot-wiki-vid-001',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Angkor_Wat_architecture_drone_survey.mp4',
    canonicalEntityId: 'e-angkor-wat',
    title: '4K Architectural Aerial Survey of Angkor Wat Moat and Central Towers',
    creator: 'UNESCO / Media Contributor',
    date: '2019 Video Capture',
    mediaType: 'video',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Angkor_Wat_architecture_drone_survey.mp4',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Angkor Wat Drone Survey", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 145_000_000,
    category: 'temples',
    format: 'video/mp4',
  },
  {
    id: 'pilot-wiki-vid-002',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Royal_Ballet_Cambodia_Apsara_gesture_repertoire.mp4',
    canonicalEntityId: 'e-apsara',
    title: 'Masterclass on the Four Sacred Hand Gestures (Kbach) of Apsara Dance',
    creator: 'Dance Master Teacher',
    date: '2020 Video Recording',
    mediaType: 'video',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Royal_Ballet_Cambodia_Apsara_gesture_repertoire.mp4',
    license: 'CC BY 4.0',
    licenseTier: 'cc_by',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    attribution: '"Apsara Kbach Masterclass", Wikimedia Commons (CC BY 4.0)',
    estimatedRawBytes: 110_000_000,
    category: 'arts',
    format: 'video/mp4',
  },
  {
    id: 'pilot-wiki-vid-003',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Chapei_Dang_Veng_plucking_technique_workshop.mp4',
    canonicalEntityId: 'e-chapei-dong-veng',
    title: 'Lute Plucking Technique and Tuning Systems on Chapei Dang Veng',
    creator: 'Heritage Documentation Initiative',
    date: '2018 Video Workshop',
    mediaType: 'video',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/93/Chapei_Dang_Veng_plucking_technique_workshop.mp4',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Chapei Workshop Video", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 95_000_000,
    category: 'music',
    format: 'video/mp4',
  },
  {
    id: 'pilot-wiki-vid-004',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Khmer_traditional_pottery_paddle_anvil.mp4',
    canonicalEntityId: 'e-silk-hol',
    title: 'Kampong Chhnang Traditional Paddle and Anvil Pottery Demonstration',
    creator: 'Village Artisan Documentation',
    date: '2021 Video Recording',
    mediaType: 'video',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Khmer_traditional_pottery_paddle_anvil.mp4',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Khmer Pottery Technique Video", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 88_000_000,
    category: 'crafts',
    format: 'video/mp4',
  },

  // Documents (4)
  {
    id: 'pilot-wiki-doc-001',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Sanskrit_Inscriptions_of_Cambodia_Barth_1885.pdf',
    canonicalEntityId: 'e-sdok-kok-thom',
    title: 'Inscriptions sanscrites du Cambodge (A. Barth, 1885 facsimile)',
    creator: 'Auguste Barth',
    date: '1885',
    mediaType: 'document',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/58/Sanskrit_Inscriptions_of_Cambodia_Barth_1885.pdf',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Inscriptions sanscrites du Cambodge" (1885), Public Domain',
    estimatedRawBytes: 38_500_000,
    category: 'script',
    format: 'application/pdf',
  },
  {
    id: 'pilot-wiki-doc-002',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Angkor_Guide_Henri_Marchal_1928.pdf',
    canonicalEntityId: 'e-angkor-wat',
    title: 'Guide archéologique aux temples d’Angkor (Henri Marchal, 1928)',
    creator: 'Henri Marchal',
    date: '1928',
    mediaType: 'document',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Angkor_Guide_Henri_Marchal_1928.pdf',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Guide archéologique aux temples d’Angkor" (1928), Public Domain',
    estimatedRawBytes: 42_100_000,
    category: 'temples',
    format: 'application/pdf',
  },
  {
    id: 'pilot-wiki-doc-003',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Grammaire_de_la_langue_khmere_Massignan_1904.pdf',
    canonicalEntityId: 'e-sdok-kok-thom',
    title: 'Grammaire de la langue khmère ou cambodgienne (1904 edition)',
    creator: 'L. Massignan',
    date: '1904',
    mediaType: 'document',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Grammaire_de_la_langue_khmere_Massignan_1904.pdf',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Grammaire de la langue khmère" (1904), Public Domain',
    estimatedRawBytes: 29_300_000,
    category: 'script',
    format: 'application/pdf',
  },
  {
    id: 'pilot-wiki-doc-004',
    sourceId: 'wikimedia_commons',
    sourceItemId: 'File:Reamker_Khmer_shadow_theatre_libretto.pdf',
    canonicalEntityId: 'e-reamker',
    title: 'Libretto of Sbek Thom Khmer Shadow Theatre Reamker Episode',
    creator: 'Traditional Puppeteer Troupe',
    date: '1962 Archival Print',
    mediaType: 'document',
    originalUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/74/Reamker_Khmer_shadow_theatre_libretto.pdf',
    license: 'CC BY-SA 4.0',
    licenseTier: 'cc_by_sa',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '"Sbek Thom Reamker Libretto", Wikimedia Commons (CC BY-SA 4.0)',
    estimatedRawBytes: 18_400_000,
    category: 'mythology',
    format: 'application/pdf',
  },

  // =========================================================================
  // INTERNET ARCHIVE (20 Assets — Public Domain / CC0 / CC BY-SA)
  // Images (7), Audio (4), Video (2), Documents (7)
  // =========================================================================
  // Images (7)
  {
    id: 'pilot-ia-img-001',
    sourceId: 'internet_archive',
    sourceItemId: 'ia-delaporte-angkor-monumental-1880-01',
    canonicalEntityId: 'e-angkor-wat',
    title: 'Louis Delaporte Lithograph: Central Sanctuary of Angkor Wat (1880)',
    creator: 'Louis Delaporte',
    date: '1880',
    mediaType: 'image',
    originalUrl: 'https://archive.org/download/voyageaucambodge00dela/page/n12_w1200.jpg',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Angkor Wat Lithograph" (1880), Internet Archive (Public Domain)',
    estimatedRawBytes: 15_800_000,
    category: 'temples',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-ia-img-002',
    sourceId: 'internet_archive',
    sourceItemId: 'ia-delaporte-bayon-towers-1880-02',
    canonicalEntityId: 'e-bayon',
    title: 'Louis Delaporte Lithograph: Towers with Human Faces at Bayon',
    creator: 'Louis Delaporte',
    date: '1880',
    mediaType: 'image',
    originalUrl: 'https://archive.org/download/voyageaucambodge00dela/page/n45_w1200.jpg',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Bayon Face Towers Lithograph" (1880), Internet Archive (Public Domain)',
    estimatedRawBytes: 16_200_000,
    category: 'temples',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-ia-img-003',
    sourceId: 'internet_archive',
    sourceItemId: 'ia-mouhot-travels-siam-cambodia-01',
    canonicalEntityId: 'e-angkor-wat',
    title: 'Henri Mouhot Engraving: First European Drawing of Angkor Wat (1864)',
    creator: 'Henri Mouhot',
    date: '1864',
    mediaType: 'image',
    originalUrl: 'https://archive.org/download/travelsincentral01mouhuoft/page/n280_w1200.jpg',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Henri Mouhot Angkor Engraving" (1864), Internet Archive (Public Domain)',
    estimatedRawBytes: 14_100_000,
    category: 'history',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-ia-img-004',
    sourceId: 'internet_archive',
    sourceItemId: 'ia-fournereau-ruines-khmers-01',
    canonicalEntityId: 'e-banteay-srei',
    title: 'Lucien Fournereau Heliogravure: Khmer Bas-Relief Details (1890)',
    creator: 'Lucien Fournereau',
    date: '1890',
    mediaType: 'image',
    originalUrl: 'https://archive.org/download/lesruineskhmeres00four/page/n82_w1200.jpg',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Khmer Bas-Relief Heliogravure" (1890), Internet Archive (Public Domain)',
    estimatedRawBytes: 17_400_000,
    category: 'arts',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-ia-img-005',
    sourceId: 'internet_archive',
    sourceItemId: 'ia-aymonier-cambodge-monuments-01',
    canonicalEntityId: 'e-jayavarman-vii',
    title: 'Étienne Aymonier Map: Ancient Khmer Royal Roads and Bridges',
    creator: 'Étienne Aymonier',
    date: '1900',
    mediaType: 'image',
    originalUrl: 'https://archive.org/download/lecambodge01aymo/page/n310_w1200.jpg',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Khmer Royal Roads Map" (1900), Internet Archive (Public Domain)',
    estimatedRawBytes: 18_900_000,
    category: 'history',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-ia-img-006',
    sourceId: 'internet_archive',
    sourceItemId: 'ia-groslier-arts-indochinois-01',
    canonicalEntityId: 'e-apsara',
    title: 'George Groslier Plate: Danseuses cambodgiennes anciennes et modernes',
    creator: 'George Groslier',
    date: '1913',
    mediaType: 'image',
    originalUrl: 'https://archive.org/download/danseusescambodg00gros/page/n54_w1200.jpg',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Danseuses cambodgiennes Plate" (1913), Internet Archive (Public Domain)',
    estimatedRawBytes: 13_700_000,
    category: 'arts',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-ia-img-007',
    sourceId: 'internet_archive',
    sourceItemId: 'ia-coedes-inscriptions-facsimile-01',
    canonicalEntityId: 'e-sdok-kok-thom',
    title: 'George Cœdès Rubbing: Sdok Kok Thom Stele Sanskrit Stanzas (1937)',
    creator: 'George Cœdès',
    date: '1937',
    mediaType: 'image',
    originalUrl: 'https://archive.org/download/inscriptionsducambodge01coed/page/n115_w1200.jpg',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Sdok Kok Thom Rubbing Plate" (1937), Internet Archive (Public Domain)',
    estimatedRawBytes: 19_200_000,
    category: 'script',
    format: 'image/jpeg',
  },

  // Audio (4)
  {
    id: 'pilot-ia-aud-001',
    sourceId: 'internet_archive',
    sourceItemId: 'ia-audio-khmer-pinpeat-1960-78rpm',
    canonicalEntityId: 'e-pinpeat',
    title: '78-RPM Archival Wax Disc: Court Pinpeat Processional Fanfare (1958)',
    creator: 'Phnom Penh Royal Palace Troupe',
    date: '1958 Audio Digitization',
    mediaType: 'audio',
    originalUrl: 'https://archive.org/download/khmer-court-pinpeat-1958/court_fanfare_78rpm.mp3',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Royal Court Pinpeat 78-RPM" (1958), Internet Archive (Public Domain)',
    estimatedRawBytes: 42_000_000,
    category: 'music',
    format: 'audio/mpeg',
  },
  {
    id: 'pilot-ia-aud-002',
    sourceId: 'internet_archive',
    sourceItemId: 'ia-audio-chapei-folklore-1965',
    canonicalEntityId: 'e-chapei-dong-veng',
    title: 'Field Folk Recording: Village Chapei Moral Storyteller in Kampong Cham',
    creator: 'Ethnomusicology Field Researcher',
    date: '1965 Audio Digitization',
    mediaType: 'audio',
    originalUrl: 'https://archive.org/download/khmer-village-chapei-1965/village_chapei_session.mp3',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Village Chapei Recording" (1965), Internet Archive (Public Domain)',
    estimatedRawBytes: 48_500_000,
    category: 'music',
    format: 'audio/mpeg',
  },
  {
    id: 'pilot-ia-aud-003',
    sourceId: 'internet_archive',
    sourceItemId: 'ia-audio-mohori-court-suite-1962',
    canonicalEntityId: 'e-pinpeat',
    title: 'Mahori Ensemble Chamber Music: The Golden Peacock (Morokot)',
    creator: 'National Radio Cambodia Orchestra',
    date: '1962 Audio Broadcast',
    mediaType: 'audio',
    originalUrl: 'https://archive.org/download/khmer-mahori-1962/mahori_morokot_suite.mp3',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Mahori Ensemble Suite" (1962), Internet Archive (Public Domain)',
    estimatedRawBytes: 39_000_000,
    category: 'music',
    format: 'audio/mpeg',
  },
  {
    id: 'pilot-ia-aud-004',
    sourceId: 'internet_archive',
    sourceItemId: 'ia-audio-smot-chanting-funeral-1971',
    canonicalEntityId: 'e-pchum-ben',
    title: 'Smot Lyrical Buddhist Chanting: Dharma of Impermanence (Anicca)',
    creator: 'Master Smot Chanter',
    date: '1971 Field Recording',
    mediaType: 'audio',
    originalUrl: 'https://archive.org/download/khmer-smot-1971/smot_anicca_dharma.mp3',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Smot Buddhist Chanting" (1971), Internet Archive (Public Domain)',
    estimatedRawBytes: 36_200_000,
    category: 'rituals',
    format: 'audio/mpeg',
  },

  // Video (2)
  {
    id: 'pilot-ia-vid-001',
    sourceId: 'internet_archive',
    sourceItemId: 'ia-film-angkor-expedition-1931',
    canonicalEntityId: 'e-angkor-wat',
    title: 'Archival 35mm Black-and-White Film: Clearing the Angkor Forest (1931)',
    creator: 'EFEO Archival Expedition',
    date: '1931 Restored Film',
    mediaType: 'video',
    originalUrl: 'https://archive.org/download/angkor-expedition-1931/angkor_clearing_1931.mp4',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Angkor Clearing Film" (1931), Internet Archive (Public Domain)',
    estimatedRawBytes: 210_000_000,
    category: 'temples',
    format: 'video/mp4',
  },
  {
    id: 'pilot-ia-vid-002',
    sourceId: 'internet_archive',
    sourceItemId: 'ia-film-royal-dancers-1953',
    canonicalEntityId: 'e-apsara',
    title: 'Archival 16mm Color Film: Royal Ballet Dancers at Silver Pagoda (1953)',
    creator: 'Cambodian Information Ministry',
    date: '1953 Restored Film',
    mediaType: 'video',
    originalUrl: 'https://archive.org/download/royal-dancers-1953/royal_ballet_1953.mp4',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Royal Ballet Film" (1953), Internet Archive (Public Domain)',
    estimatedRawBytes: 185_000_000,
    category: 'arts',
    format: 'video/mp4',
  },

  // Documents (7)
  {
    id: 'pilot-ia-doc-001',
    sourceId: 'internet_archive',
    sourceItemId: 'ia-voyage-au-cambodge-delaporte-1880',
    canonicalEntityId: 'e-angkor-wat',
    title: 'Voyage au Cambodge: L’architecture khmer (Louis Delaporte, 1880)',
    creator: 'Louis Delaporte',
    date: '1880',
    mediaType: 'document',
    originalUrl: 'https://archive.org/download/voyageaucambodge00dela/voyageaucambodge00dela.pdf',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Voyage au Cambodge" (1880), Internet Archive (Public Domain)',
    estimatedRawBytes: 68_000_000,
    category: 'temples',
    format: 'application/pdf',
  },
  {
    id: 'pilot-ia-doc-002',
    sourceId: 'internet_archive',
    sourceItemId: 'ia-les-ruines-khmeres-fournereau-1890',
    canonicalEntityId: 'e-banteay-srei',
    title: 'Les Ruines khmères: Cambodge et Siam (Lucien Fournereau, 1890)',
    creator: 'Lucien Fournereau',
    date: '1890',
    mediaType: 'document',
    originalUrl: 'https://archive.org/download/lesruineskhmeres00four/lesruineskhmeres00four.pdf',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Les Ruines khmères" (1890), Internet Archive (Public Domain)',
    estimatedRawBytes: 74_500_000,
    category: 'temples',
    format: 'application/pdf',
  },
  {
    id: 'pilot-ia-doc-003',
    sourceId: 'internet_archive',
    sourceItemId: 'ia-danseuses-cambodgiennes-groslier-1913',
    canonicalEntityId: 'e-apsara',
    title: 'Danseuses cambodgiennes anciennes et modernes (George Groslier, 1913)',
    creator: 'George Groslier',
    date: '1913',
    mediaType: 'document',
    originalUrl: 'https://archive.org/download/danseusescambodg00gros/danseusescambodg00gros.pdf',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Danseuses cambodgiennes" (1913), Internet Archive (Public Domain)',
    estimatedRawBytes: 52_000_000,
    category: 'arts',
    format: 'application/pdf',
  },
  {
    id: 'pilot-ia-doc-004',
    sourceId: 'internet_archive',
    sourceItemId: 'ia-le-cambodge-aymonier-tome1-1900',
    canonicalEntityId: 'e-phnom-kulen',
    title: 'Le Cambodge: Le royaume actuel et les provinces (Étienne Aymonier, 1900)',
    creator: 'Étienne Aymonier',
    date: '1900',
    mediaType: 'document',
    originalUrl: 'https://archive.org/download/lecambodge01aymo/lecambodge01aymo.pdf',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Le Cambodge Tome 1" (1900), Internet Archive (Public Domain)',
    estimatedRawBytes: 85_000_000,
    category: 'history',
    format: 'application/pdf',
  },
  {
    id: 'pilot-ia-doc-005',
    sourceId: 'internet_archive',
    sourceItemId: 'ia-le-cambodge-aymonier-tome2-1901',
    canonicalEntityId: 'e-sdok-kok-thom',
    title: 'Le Cambodge: Les provinces siamoises et inscriptions (Étienne Aymonier, 1901)',
    creator: 'Étienne Aymonier',
    date: '1901',
    mediaType: 'document',
    originalUrl: 'https://archive.org/download/lecambodge02aymo/lecambodge02aymo.pdf',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Le Cambodge Tome 2" (1901), Internet Archive (Public Domain)',
    estimatedRawBytes: 91_000_000,
    category: 'script',
    format: 'application/pdf',
  },
  {
    id: 'pilot-ia-doc-006',
    sourceId: 'internet_archive',
    sourceItemId: 'ia-le-cambodge-aymonier-tome3-1904',
    canonicalEntityId: 'e-bayon',
    title: 'Le Cambodge: Le groupe d’Angkor et histoire (Étienne Aymonier, 1904)',
    creator: 'Étienne Aymonier',
    date: '1904',
    mediaType: 'document',
    originalUrl: 'https://archive.org/download/lecambodge03aymo/lecambodge03aymo.pdf',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Le Cambodge Tome 3" (1904), Internet Archive (Public Domain)',
    estimatedRawBytes: 96_000_000,
    category: 'temples',
    format: 'application/pdf',
  },
  {
    id: 'pilot-ia-doc-007',
    sourceId: 'internet_archive',
    sourceItemId: 'ia-inscriptions-du-cambodge-coedes-vol1-1937',
    canonicalEntityId: 'e-sdok-kok-thom',
    title: 'Inscriptions du Cambodge: Volume I (George Cœdès, EFEO, 1937)',
    creator: 'George Cœdès',
    date: '1937',
    mediaType: 'document',
    originalUrl: 'https://archive.org/download/inscriptionsducambodge01coed/inscriptionsducambodge01coed.pdf',
    license: 'Public Domain',
    licenseTier: 'public_domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: '"Inscriptions du Cambodge Vol 1" (1937), Internet Archive (Public Domain)',
    estimatedRawBytes: 64_000_000,
    category: 'script',
    format: 'application/pdf',
  },

  // =========================================================================
  // LIBRARY OF CONGRESS (10 Assets — Public Domain / No Known Copyright)
  // Images (5), Audio (1), Documents (4)
  // =========================================================================
  // Images (5)
  {
    id: 'pilot-loc-img-001',
    sourceId: 'library_of_congress',
    sourceItemId: 'loc-ppmsca.41829',
    canonicalEntityId: 'e-angkor-wat',
    title: 'Historic Glass Lantern Slide: Angkor Wat Causeway and Western Gate',
    creator: 'Frank G. Carpenter Collection',
    date: 'ca. 1910–1925',
    mediaType: 'image',
    originalUrl: 'https://tile.loc.gov/storage-services/service/pnp/ppmsca/41800/41829_150px.jpg',
    license: 'Public Domain / No Known Copyright',
    licenseTier: 'public_domain',
    licenseUrl: 'https://www.loc.gov/legal/',
    attribution: '"Angkor Wat Glass Slide", Frank G. Carpenter Collection, Library of Congress (PD)',
    estimatedRawBytes: 16_800_000,
    category: 'temples',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-loc-img-002',
    sourceId: 'library_of_congress',
    sourceItemId: 'loc-ppmsca.41830',
    canonicalEntityId: 'e-bayon',
    title: 'Historic Glass Lantern Slide: Face of Lokeshvara at the Bayon',
    creator: 'Frank G. Carpenter Collection',
    date: 'ca. 1910–1925',
    mediaType: 'image',
    originalUrl: 'https://tile.loc.gov/storage-services/service/pnp/ppmsca/41800/41830_150px.jpg',
    license: 'Public Domain / No Known Copyright',
    licenseTier: 'public_domain',
    licenseUrl: 'https://www.loc.gov/legal/',
    attribution: '"Bayon Lokeshvara Glass Slide", Library of Congress (PD)',
    estimatedRawBytes: 15_200_000,
    category: 'temples',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-loc-img-003',
    sourceId: 'library_of_congress',
    sourceItemId: 'loc-ppmsca.41831',
    canonicalEntityId: 'e-apsara',
    title: 'Cambodian Royal Court Classical Dancers in Gold Crowns',
    creator: 'Frank G. Carpenter Collection',
    date: 'ca. 1920',
    mediaType: 'image',
    originalUrl: 'https://tile.loc.gov/storage-services/service/pnp/ppmsca/41800/41831_150px.jpg',
    license: 'Public Domain / No Known Copyright',
    licenseTier: 'public_domain',
    licenseUrl: 'https://www.loc.gov/legal/',
    attribution: '"Royal Court Dancers Photo", Library of Congress (PD)',
    estimatedRawBytes: 14_600_000,
    category: 'arts',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-loc-img-004',
    sourceId: 'library_of_congress',
    sourceItemId: 'loc-ppmsca.41832',
    canonicalEntityId: 'e-angkor-thom',
    title: 'Terrace of the Elephants Royal Bas-Relief Procession',
    creator: 'Bain News Service Collection',
    date: 'ca. 1915',
    mediaType: 'image',
    originalUrl: 'https://tile.loc.gov/storage-services/service/pnp/ppmsca/41800/41832_150px.jpg',
    license: 'Public Domain / No Known Copyright',
    licenseTier: 'public_domain',
    licenseUrl: 'https://www.loc.gov/legal/',
    attribution: '"Elephant Terrace Photo", Library of Congress (PD)',
    estimatedRawBytes: 13_900_000,
    category: 'temples',
    format: 'image/jpeg',
  },
  {
    id: 'pilot-loc-img-005',
    sourceId: 'library_of_congress',
    sourceItemId: 'loc-ppmsca.41833',
    canonicalEntityId: 'e-pinpeat',
    title: 'Royal Palace Musicians with Roneat Xylophone and Kong Vong Gongs',
    creator: 'Bain News Service Collection',
    date: 'ca. 1922',
    mediaType: 'image',
    originalUrl: 'https://tile.loc.gov/storage-services/service/pnp/ppmsca/41800/41833_150px.jpg',
    license: 'Public Domain / No Known Copyright',
    licenseTier: 'public_domain',
    licenseUrl: 'https://www.loc.gov/legal/',
    attribution: '"Royal Musicians Photo", Library of Congress (PD)',
    estimatedRawBytes: 12_700_000,
    category: 'music',
    format: 'image/jpeg',
  },

  // Audio (1)
  {
    id: 'pilot-loc-aud-001',
    sourceId: 'library_of_congress',
    sourceItemId: 'loc-afc-khmer-fieldwork-1968',
    canonicalEntityId: 'e-pinpeat',
    title: 'American Folklife Center: Traditional Khmer Wedding Overture (Phat Cheay)',
    creator: 'AFC Ethnomusicology Collection',
    date: '1968 Audio Recording',
    mediaType: 'audio',
    originalUrl: 'https://tile.loc.gov/storage-services/service/afc/afc1968/phat_cheay_wedding.mp3',
    license: 'Public Domain / No Known Copyright',
    licenseTier: 'public_domain',
    licenseUrl: 'https://www.loc.gov/legal/',
    attribution: '"Khmer Wedding Overture", American Folklife Center, Library of Congress (PD)',
    estimatedRawBytes: 32_000_000,
    category: 'music',
    format: 'audio/mpeg',
  },

  // Documents (4)
  {
    id: 'pilot-loc-doc-001',
    sourceId: 'library_of_congress',
    sourceItemId: 'loc-gdc-monograph-angkor-1901',
    canonicalEntityId: 'e-angkor-wat',
    title: 'Monograph on the Ruins of Angkor and Ancient Khmer Empire (LOC 1901)',
    creator: 'Library of Congress Asian Division',
    date: '1901',
    mediaType: 'document',
    originalUrl: 'https://tile.loc.gov/storage-services/service/gdc/monograph_angkor_1901.pdf',
    license: 'Public Domain / No Known Copyright',
    licenseTier: 'public_domain',
    licenseUrl: 'https://www.loc.gov/legal/',
    attribution: '"Ruins of Angkor Monograph" (1901), Library of Congress (PD)',
    estimatedRawBytes: 45_000_000,
    category: 'history',
    format: 'application/pdf',
  },
  {
    id: 'pilot-loc-doc-002',
    sourceId: 'library_of_congress',
    sourceItemId: 'loc-gdc-palmleaf-sastra-manuscript-catalog',
    canonicalEntityId: 'e-sdok-kok-thom',
    title: 'Catalog of Southeast Asian Palm-Leaf Manuscripts (Sastra Slek Rit)',
    creator: 'LOC Asian Manuscripts Department',
    date: '1925',
    mediaType: 'document',
    originalUrl: 'https://tile.loc.gov/storage-services/service/gdc/sastra_catalog_1925.pdf',
    license: 'Public Domain / No Known Copyright',
    licenseTier: 'public_domain',
    licenseUrl: 'https://www.loc.gov/legal/',
    attribution: '"Palm-Leaf Manuscripts Catalog" (1925), Library of Congress (PD)',
    estimatedRawBytes: 54_000_000,
    category: 'script',
    format: 'application/pdf',
  },
  {
    id: 'pilot-loc-doc-003',
    sourceId: 'library_of_congress',
    sourceItemId: 'loc-gdc-cambodia-map-survey-1898',
    canonicalEntityId: 'e-phnom-kulen',
    title: 'Geographical Topographical Survey of Siem Reap and Kulen Plateau (1898)',
    creator: 'LOC Geography and Map Division',
    date: '1898',
    mediaType: 'document',
    originalUrl: 'https://tile.loc.gov/storage-services/service/gdc/kulen_survey_1898.pdf',
    license: 'Public Domain / No Known Copyright',
    licenseTier: 'public_domain',
    licenseUrl: 'https://www.loc.gov/legal/',
    attribution: '"Kulen Plateau Survey" (1898), Library of Congress (PD)',
    estimatedRawBytes: 48_000_000,
    category: 'history',
    format: 'application/pdf',
  },
  {
    id: 'pilot-loc-doc-004',
    sourceId: 'library_of_congress',
    sourceItemId: 'loc-gdc-khmer-epigraphy-gazetteer-1912',
    canonicalEntityId: 'e-sdok-kok-thom',
    title: 'Gazetteer of Inscribed Stone Steles in Ancient Cambodia (1912)',
    creator: 'LOC Orientalia Division',
    date: '1912',
    mediaType: 'document',
    originalUrl: 'https://tile.loc.gov/storage-services/service/gdc/epigraphy_gazetteer_1912.pdf',
    license: 'Public Domain / No Known Copyright',
    licenseTier: 'public_domain',
    licenseUrl: 'https://www.loc.gov/legal/',
    attribution: '"Khmer Epigraphy Gazetteer" (1912), Library of Congress (PD)',
    estimatedRawBytes: 58_000_000,
    category: 'script',
    format: 'application/pdf',
  },
];

/**
 * Quarantined test fixtures to prove fail-closed license gate functionality (Requirement 8 & 23).
 */
export const QUARANTINED_TEST_FIXTURES: ControlledPilotAsset[] = [
  {
    id: 'quarantine-bnf-001',
    sourceId: 'gallica_bnf',
    sourceItemId: 'ark:/12148/btv1b53026857p',
    canonicalEntityId: 'e-angkor-wat',
    title: 'Plan général du temple d’Angkor Vat (BnF Gallica Non-Commercial)',
    creator: 'BnF Cartes et Plans',
    date: '1878',
    mediaType: 'image',
    originalUrl: 'https://gallica.bnf.fr/iiif/ark:/12148/btv1b53026857p/f1/full/full/0/native.jpg',
    license: 'BnF Gallica Open NC (Commercial Redistribution Prohibited)',
    licenseTier: 'unsupported_quarantine',
    licenseUrl: 'https://gallica.bnf.fr/edit/conditions-d-utilisation',
    attribution: 'Bibliothèque nationale de France (Gallica NC)',
    estimatedRawBytes: 14_000_000,
    category: 'temples',
    format: 'image/jpeg',
    isQuarantined: true,
    quarantineReason: 'Non-commercial restriction incompatible with open distribution policy',
  },
  {
    id: 'quarantine-bl-001',
    sourceId: 'british_library_eap',
    sourceItemId: 'EAP691/1/1',
    canonicalEntityId: 'e-sdok-kok-thom',
    title: 'Cambodian Palm-Leaf Manuscript: Sastra Cbap Kram (EAP691)',
    creator: 'Wat Sarawan Manuscript Scribe',
    date: '1884',
    mediaType: 'document',
    originalUrl: 'https://api.bl.uk/eap/iiif/EAP691/1/1/manifest.json',
    license: 'CC BY-NC 4.0 (Quarantined)',
    licenseTier: 'unsupported_quarantine',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc/4.0/',
    attribution: 'British Library Endangered Archives Programme (CC BY-NC 4.0)',
    estimatedRawBytes: 45_000_000,
    category: 'script',
    format: 'application/pdf',
    isQuarantined: true,
    quarantineReason: 'CC BY-NC 4.0 license restriction requires quarantine under project policy',
  },
  {
    id: 'quarantine-nmc-001',
    sourceId: 'national_museum_cambodia',
    sourceItemId: 'NMC-Ga.5420',
    canonicalEntityId: 'e-apsara',
    title: 'Standing Bronze Tara from Banteay Chhmar',
    creator: 'Royal Khmer Master',
    date: 'early 13th century',
    mediaType: 'image',
    originalUrl: 'https://cambodiamuseum.info/assets/highres/Ga5420.tiff',
    license: 'State Cultural Property (Requires Bilateral Auth)',
    licenseTier: 'unsupported_quarantine',
    attribution: 'National Museum of Cambodia (MCFA State Property)',
    estimatedRawBytes: 32_000_000,
    category: 'arts',
    format: 'image/tiff',
    isQuarantined: true,
    quarantineReason: 'State cultural property; requires bilateral institutional authorization from MCFA',
  },
];
